<?php
	if (is_null($this->vars))
	{
		$this->vars = array();
	}
?>
<div class="row">
	<?php foreach($this->vars as $var): ?>
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><?php echo $var['title']; ?></h3>
					</div>
					<div class="panel-body">
						<?php echo $var['text']; ?>
					</div>
				</div>
			</div>
	<?php endforeach; ?>
</div>