<div class="jumbotron">
	Some Text Mod3
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Some Title Mod3</h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf('Mod3') ?></p>
                <p><?php echo __FILE__; ?></p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>