
<div class="jumbotron">
	<?php echo $country->getName(); ?>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $country->getName(); ?></h3>
            </div>
            <div class="panel-body">
	            <?php echo $country->getDescription(); ?>
            </div>
        </div>
    </div>
</div>