<div class="jumbotron">
	Some Text
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Some Title</h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf('Mod1') ?></p>
                <p><?php echo __FILE__; ?></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">

    </div>

    <div class="col-md-4">

    </div>
</div>
<?php if (is_array($this->vars)): ?>
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Some Vars</h3>
				</div>
				<div class="panel-body">
					<?php
						foreach($this->vars as $var)
						{
							echo '<p>' . $var . '</p>';
						}
					?>
				</div>
			</div>
		</div>
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
		</div>
	</div>
<?php endif; ?>
