<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('AppLayout')->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
			->prependStylesheet($this->basePath('css/style.css'))
			->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
			->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

		<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basePath('js/bootstrap.min.js'))
			->prependFile($this->basePath('js/jquery.min.js'))
			->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
		; ?>
	</head>
	<body>
		<h4><?php echo __FILE__; ?></h4>
		<?php
			foreach ($this->flashMessages() as $k => $messages)
			{
				foreach ($messages as $message)
				{
					echo '<div class="alert alert-' . $k . '" role="alert">';
					echo $message;
					echo '</div>';
				}
			}
		?>
		<div class="row">
			<div class="col-md-2">
				<?php
				$this->menu();
				?>
				<?php if ($this->panelLeft) : ?>
					<div data-role="panel-left">
						<?php echo $this->panelLeft ?>
					</div>
				<?php endif; ?>
			</div>
			<div class="col-md-8">
				<div class="panel panel-default">
					<div class="panel-body">
						<?php echo $this->content; ?>
					</div>
				</div>
			</div>
			<div class="col-md-2">
				<?php if ($this->panelRight) : ?>
					<div data-role="panel-left">
						<?php echo $this->panelRight ?>
					</div>
				<?php endif; ?>
			</div>
		</div>
	</body>
</html>

