<div class="jumbotron">
	Some Text
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Some Title</h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf('ssssssssssssss') ?></p>
                <p>wwwwww</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">

    </div>

    <div class="col-md-4">

    </div>
</div>
